export const ROUTES = {
  Home: '/',
  Messenger: '/messenger',
  Help: '/help',
  NoSidebar: '/blog/no_sidebar',
  Login: '/auth/login',
  SignUp: '/auth/signup',
  LinkIdentifier: '/auth/link_identifier',
  LinkPassword: '/auth/link_password',
  ForgotPassword: '/auth/forgot_password',
  VerifyOtp: '/auth/verify_otp',
  ResetPassword: '/auth/reset_password',
  BlockedFriends: '/messenger/block_friends',
  Contact: '/messenger/contact',
  Favorite: '/messenger/favorite',
  Friends: '/messenger/friends',
  Notifications: '/messenger/notifications',
  Settings: '/messenger/settings',
  Status: '/messenger/status',
  Document: '/messenger/document',
  Subscription: '/subscription',
  Payment: '/payment',
}
